#!/bin/bash
style='{ BasedOnStyle: Chromium, Standard: C++03, Cpp11BracedListStyle: false, AlwaysBreakTemplateDeclarations: false }'
dir="$(dirname $0)/.."
find "$dir" \( -iname '*.c' -or -iname '*.cpp' -or -iname '*.h' \) \
	\! -iname 'cmdline.h' \
	\! -ipath "$dir/lib/*" \
	\! -ipath "$dir/doc/*" \
	-exec clang-format -style="$style" -i {} +
